name: run terraform and release
on:
  push:
    branches:
      - blinx-change

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::533267356181:role/github-ci-role
          aws-region: eu-west-2

      - name: Run terraform
        working-directory: pipeline/terraform/mhs-environment
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve

     